 <ul class="ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all">
  <li id="hom" class="ui-state-default ui-corner-top"><a href="<?php echo SITE_PATH; ?>/admin/" title="Go to home page">Home</a></li>
  <li id="blo" class="ui-state-default ui-corner-top"><a href="javascript:void(0);" onclick="javascript:block();listpage('blog');" title="List posts of blog">Blog</a></li>
  <li id="ema" class="ui-state-default ui-corner-top"><a href="javascript:void(0);" onclick="javascript:block();listpage('emails');" title="List emails and newsletters">Emails</a></li>
  <li id="ima" class="ui-state-default ui-corner-top"><a href="javascript:void(0);" onclick="javascript:block();listpage('images');" title="List Images">Images</a></li>
  <li id="new" class="ui-state-default ui-corner-top"><a href="javascript:void(0);" onclick="javascript:block();listpage('newsletter');" title="List Newsletter">Newsletter</a></li>
  <li id="pag" class="ui-state-default ui-corner-top"><a href="javascript:void(0);" onclick="javascript:block();listpage('pages');" title="List Pages">Pages</a></li>
  <li id="use" class="ui-state-default ui-corner-top"><a href="javascript:void(0);" onclick="javascript:block();listpage('users');" title="List users">Users</a></li>
  <!-- <li id="ude" class="ui-state-default ui-corner-top"><a href="javascript:void(0);" onclick="javascript:block();userdetails();" title="Edit Details &amp; Password">My Account</a></li> -->
  <li id="log" class="ui-state-default ui-corner-top"><a href="<?php echo SITE_PATH; ?>/admin/logout" onclick="javascript:block();" title="Log out the system"><span style='color:yellow !important;'>Logout</span></a></li>
  <!-- <li id="wid" class="ui-state-default ui-corner-top"><a class="ui-widget ui-widget-content" href="javascript:void(0);"><span id="themeswitch"></span></a></li> -->
 </ul>
