 <?php echo $this->doctype() . "\n";?>
<html xmlns="http://www.w3.org/1999/xhtml">
 <head>
<?php echo $this->render('head.phtml') . "\n";?>
 </head>
 <body>
  <div id="topbar"></div>
  <div id="layout">
   <div id="maincontent">
<?php echo $this->layout()->content; ?>
   </div>
  </div>
  <div id="bottombar"><div id="bottombarback"></div></div>
  <div id="footer">
<?php echo $this->render('footer.phtml') . "\n";?>
  </div>
 </body>
</html>
