<?php 
if(count($this->post) > 0)
{
	$post = $this->post;
	$cdate = strtotime($post['cdate']);
	$cdate = date('d/m/Y g:ia', $cdate);
	$urltoback = $_SERVER['HTTP_REFERER'] != "" ? $_SERVER['HTTP_REFERER'] : "/blog/";
?>
    <div class="menucentertop"></div>
    <div class="menucentermiddle">
<?php
	if($post['display'] == '1')
	{
?>
     <h1><a href="/blog/<?php echo $post['url']; ?>.html"><?php echo utf8_encode(stripslashes($post['title'])); ?></a></h1>
     <?php echo utf8_encode(stripslashes($post['post'])); ?>
     <div style='float:right;margin:10px 10px 0 0;font-size:11px;'><?php echo $cdate; ?></div>
     
	 </div>
    <div class="menucenterbottom"></div>
    <div class="menucenterclear"></div>

    <div id="pagination"><a class="button" href="<?php echo $urltoback; ?>">&laquo; Voltar</a></div>

    <style>#disqus_thread{margin:10px 55px 10px 35px !important;}</style>
    <div id="disqus_thread"></div>
<script type="text/javascript">
var disqus_shortname = 'lucianomarinho';
var disqus_identifier = '<?php echo md5("http://" . $_SERVER['SERVER_NAME'] . "/blog/" . $post['url'] . ".html"); ?>';
var disqus_url = 'http://<?php echo $_SERVER['SERVER_NAME']; ?>/blog/<?php echo $post['url']; ?>.html';
var disqus_title = 'Blog - <?php echo utf8_encode(stripslashes($post['title'])); ?>'; 
(function(){
	var dsq = document.createElement('script');
	dsq.type = 'text/javascript';
	dsq.async = true;
	dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';
	(document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<?php
	}
	else
	{
?>
     <h1>Esta postagem não está mais disponível ou não existe mais aqui</h1>
	 <p>Você pode voltar a página inicial e ver outras coisas legais do meu site, que tal ?!</p>
	 <p>&nbsp;</p>
     <center><a class="button" href="<?php echo $urltoback; ?>">&laquo; Voltar</a></center>
	 </div>
    <div class="menucenterbottom"></div>
    <div class="menucenterclear"></div>
<?php
	}
?>
    <div id="pagination">
     <ul id="socialbuttonnav">
      <li><!-- Google plus one--><div><g:plusone size="tall" count="true"></g:plusone></div></li>
      <li><!-- Twitter--><div><a name="twitter_share" data-count="vertical" href="http://twitter.com/share" class="twitter-share-button" >Tweet</a></div></li>
      <li id="fb"><!-- Facebook like--><div id="fb-root"></div><script src="http://connect.facebook.net/en_US/all.js#xfbml=1"></script><fb:like href="" send="false" layout="box_count" width="64" show_faces="false" action="like" font=""></fb:like></li>
      <li><!-- linkedin--><div><script type="in/share" data-counter="top"></script></div></li>
      <li><!-- stumbleupon--><div><script src="http://www.stumbleupon.com/hostedbadge.php?s=5"></script></div></li>
      <li><!-- digg--><div><a class="DiggThisButton DiggMedium" href="http://digg.com/submit?url=<?php echo urlencode($_SERVER['SCRIPT_URI']); ?>&amp;title=<?php  ?>"></a></div></li>
      <li><!-- Buzz--><div><a title="Post to Google Buzz" class="google-buzz-button" href="http://www.google.com/buzz/post" data-button-style="normal-count"></a></div></li>
     </ul>
    </div>
    
<?php
}
else if(count($this->datalist) > 0)
{
	foreach($this->datalist as $dl)
	{
		$cdate = strtotime($dl['cdate']);
		$cdate = date('d/m/Y g:ia', $cdate);
?>
    <div class="menucentertop"></div>
    <div class="menucentermiddle">
     <h1><a href="/blog/<?php echo $dl['url']; ?>.html"><?php echo utf8_encode(stripslashes($dl['title'])); ?></a></h1>
     <p><?php echo utf8_encode(stripslashes($dl['meta_description'])); ?></p>
     <div style='float:right;margin:10px 10px 0 0;font-size:11px;'><?php echo $cdate; ?></div>
    </div>
    <div class="menucenterbottom"></div>
    <div class="menucenterclear"></div>
<?php
	}

	if($this->paginator->count() > 1)
	{
		echo "<div class=\"menucenterclear\"></div>\n";
		echo $this->paginationControl($this->paginator, 'Elastic', 'index' . DS . 'pagination.phtml');
		echo "<div class=\"menucenterclear\"></div>\n";
	}
?>

    <div id="pagination">
     <ul id="socialbuttonnav">
      <li><!-- Google plus one--><div><g:plusone size="tall" count="true"></g:plusone></div></li>
      <li><!-- Twitter--><div><a name="twitter_share" data-count="vertical" href="http://twitter.com/share" class="twitter-share-button" >Tweet</a></div></li>
      <li id="fb"><!-- Facebook like--><div id="fb-root"></div><script src="http://connect.facebook.net/en_US/all.js#xfbml=1"></script><fb:like href="" send="false" layout="box_count" width="64" show_faces="false" action="like" font=""></fb:like></li>
      <li><!-- linkedin--><div><script type="in/share" data-counter="top"></script></div></li>
      <li><!-- stumbleupon--><div><script src="http://www.stumbleupon.com/hostedbadge.php?s=5"></script></div></li>
      <li><!-- digg--><div><a class="DiggThisButton DiggMedium" href="http://digg.com/submit?url=<?php echo urlencode($_SERVER['SCRIPT_URI']); ?>&amp;title=<?php  ?>"></a></div></li>
      <li><!-- Buzz--><div><a title="Post to Google Buzz" class="google-buzz-button" href="http://www.google.com/buzz/post" data-button-style="normal-count"></a></div></li>
     </ul>
    </div>
    
    <div class="menucentertop"></div>
    <div class="menucentermiddle">
     <h1>Contrate um dos serviços a seguir:</h1>
     <ul>
      <li>Criação do domínio inicial de sua empresa, .com, .com.br, como queira ou necessite</li>
      <li>Um novo site dinâmico em PHP/Mysql para sua empresa pois o atual está obsoleto</li>
      <li>Implementação de E-Commerce com PayPal/Google Checkout</li>
      <li>Hospedagem para o seu site ou de sua empresa</li>
      <li>Montagem de servidores Linux para sua empresa</li>
      <li>Um websistema interno que atenda as necessidades de sua empresa</li>
      <li>Front-End XHTML desenvolvido em Ajax/Javascript/jQuery</li>
     </ul>
     <p><a href="<?php echo SITE_PATH ?>/index/contato">Entre em contato clicando aqui ou clicando no botão "Contato" acima no menu</a></p>
    </div>
    <div class="menucenterbottom"></div>
    <div class="menucenterclear"></div>
<?php
}
?>