    <div class="menucentertop"></div>
    <div class="menucentermiddle">
     <p style="text-align:center;"><b>Entre em contato comigo através do formulário abaixo</b></p>
<?php echo $this->form; ?>
     <div id="errormsg"></div>
<script type="text/javascript">
$(document).ready(function(){
	var newButton = $(document.createElement('input'))
	.attr("type", 'text')
	.attr("value", '200')
	.attr("maxlength", "3")
	.attr("size", '3')
	.attr("name", 'remLen')
	.attr("readonly", 'readonly')
	;
	newButton.appendTo("#message-label");
});
</script>
     <p>&nbsp;</p>
    </div>
    <div class="menucenterbottom"></div>
    <div class="menucenterclear"></div>
    