<div id="pagination">
 <div id="previous">
<?php
if(isset($this->previous)){ echo "<a class='button' href='/p/" . $this->previous . "'>posts +novos</a></span>\n"; }
else{ echo "<input class='button' type='button' value='posts +novos' />\n"; }
?>
 </div>
 <div id="next">
<?php
if(isset($this->next)){ echo "<a class='button' href='/p/" . $this->next . "'>posts +antigos</a></span>\n"; }
else{ echo "<input class='button' type='button' value='posts +antigos' />\n"; }
?>
 </div>
</div>
