    <div class="menucentertop"></div>
    <div class="menucentermiddle">
     <h1>Expertise - Tecnologias Específicas</h1>
     <ul>
      <li>Programação Web PHP/Tecnologias Zend</li>
      <li>Programação de bancos de dados em MySQL, inclusíve instalação, configuração e script de backup</li>
      <li>Instalação, configuração e administração de servidor Linux/Ubuntu/Debian/Gentoo/Freebsd</li>
      <li>Apache/PUREFTPD/SSH/Samba</li>
      <li>HTML/XHTML Website Coding</li>
      <li>Programação Javascript/Jquery</li>
      <li>Ajax/Carregamento dinâmico de websites</li>
      <li>Design CSS</li>
      <li>Adobe Photoshop</li>
     </ul>
     <h2>Último aprendizado</h2>
     <p>Como um tecnologista ativo, estou sempre usando e testando as novas tecnologias web disponíveis. Estou familiarizado com a grande maioria das atualidades das tecnologias no que diz respeito ao que uso e trabalho. Tenho trabalhado atualmente com Zend Framework, este site por exemplo está todo baseado nele.</p>
    </div>
    <div class="menucenterbottom"></div>
    <div class="menucenterclear"></div>
    
    <div class="menucentertop"></div>
    <div class="menucentermiddle">
     <h1>Sites Desenvolvidos</h1>
     <ul>
      <li>Assine Agora - <a href="http://www.assinagora.com.br" target="_blank">www.assinagora.com.br</a></li>
      <li>Danny - <a href="http://www.danny.com.br" target="_blank">www.danny.com.br</a></li>
      <li>Márcio Bernardes - <a href="http://www.marciobernardes.com.br" target="_blank">www.marciobernardes.com.br</a></li>
      <li>Maurício Batista - <a href="http://www.mjbatista.com.br" target="_blank">www.mjbatista.com.br</a></li>
     </ul>
    </div>
    <div class="menucenterbottom"></div>
    <div class="menucenterclear"></div>
    
    <div class="menucentertop"></div>
    <div class="menucentermiddle">
     <h1>Sistemas Desenvolvidos e Participações</h1>
     <ul> 
      <li><a href="http://www.roquefarias.com.br/" target="_blank">www.roquefarias.com.br</a> - Desenvolvimento do sistema de buscas de imóveis em uma das versões em 2005</li>
      <li><a href="http://www.reservehotelonline.com.br/" target="_blank">www.reservehotelonline.com.br</a> - Controle interno de pousadas pela empresa <a href="http://www.brane.com.br/" target="_blank">Brane</a></li>
      <li><a href="http://www.merchantmetrix.com/" target="_blank">www.merchantmetrix.com</a> - Participação do desenvolvimento da versão 5 em 2006 pela empresa <a href="http://www.brane.com.br/" target="_blank">Brane</a> quando o sistema ainda era chamado de Apple Pie Cart</li>
      <li><a href="http://www.cetre.com.br/" target="_blank">www.cetre.com.br</a> - Desenvolvimento de todo o controle interno da empresa</li>
      <li><a href="http://www.creator.com.br/" target="_blank">www.creator.com.br</a> - Desenvolvimento de sistema interno para empresa telefônica | Administração de servidores Linux da PRODAM e PRODESP pela empresa telefônica</li>
      <li><a href="http://www.cohesp.com.br/" target="_blank">www.cohesp.com.br</a> - Participação no desenvolvimento do novo layout do site da empresa e sistema interno</li>
     </ul>
    </div>
    <div class="menucenterbottom"></div>
    <div class="menucenterclear"></div>

    <div class="menucentertop"></div>
    <div class="menucentermiddle">
     <h1>Contrate um dos serviços a seguir:</h1>
     <ul>
      <li>Criação do domínio inicial de sua empresa, .com, .com.br, como queira ou necessite</li>
      <li>Um novo site dinâmico em PHP/Mysql para sua empresa pois o atual está obsoleto</li>
      <li>Implementação de E-Commerce com PayPal/Google Checkout</li>
      <li>Hospedagem para o seu site ou de sua empresa</li>
      <li>Montagem de servidores Linux para sua empresa</li>
      <li>Um websistema interno que atenda as necessidades de sua empresa</li>
      <li>Front-End XHTML desenvolvido em Ajax/Javascript/jQuery</li>
     </ul>
     <p><a href="<?php echo SITE_PATH ?>/contato.html">Entre em contato clicando aqui ou clicando no botão "Contato" acima no menu</a></p>
    </div>
    <div class="menucenterbottom"></div>
    <div class="menucenterclear"></div>

    <ul id="socialbuttonnav">
     <li><!-- Google plus one--><div><g:plusone size="tall" count="true"></g:plusone></div></li>
     <li><!-- Twitter--><div><a name="twitter_share" data-count="vertical" href="http://twitter.com/share" class="twitter-share-button" >Tweet</a></div></li>
     <li id="fb"><!-- Facebook like--><div id="fb-root"></div><script src="http://connect.facebook.net/en_US/all.js#xfbml=1"></script><fb:like href="" send="false" layout="box_count" width="64" show_faces="false" action="like" font=""></fb:like></li>
     <li><!-- linkedin--><div><script type="in/share" data-counter="top"></script></div></li>
     <li><!-- digg--><div><a class="DiggThisButton DiggMedium" href="http://digg.com/submit?url=<?php echo urlencode($_SERVER['SCRIPT_URI']); ?>&amp;title=<?php  ?>"></a></div></li>
     <li><!-- stumbleupon--><div><script src="http://www.stumbleupon.com/hostedbadge.php?s=5"></script></div></li>
     <li><!-- Buzz--><div><a title="Post to Google Buzz" class="google-buzz-button" href="http://www.google.com/buzz/post" data-button-style="normal-count"></a></div></li>
    </ul>
