<div class="copy">
 <a href="http://www.racaboxer.com.br/" target="_blank" title="<?php echo SITE_NAME; ?>"><img style="height:16px;width:16px;" src='<?php echo SITE_PATH; ?>/favicon.ico' /> <?php echo SITE_NAME; ?> &copy; &reg; <?php echo date("Y"); ?></a><br /><br />
 Desenvolvido e mantido por: <a href="http://www.lucianomarinho.com.br/" target="_blank" title="Desenvolvido e Mantido por Luciano Marinho"><img style="border:0;height:16px;width:16px;" src='<?php echo SITE_PATH; ?>/favicon-lucianomarinho.ico' /> Luciano Marinho</a><br /><br />
 <a href="/politica-de-privacidade.html" title="Pol&iacute;tica de Privacidade">Pol&iacute;tica de Privacidade</a><br /><br />
 <a href="http://framework.zend.com/" title="Zend Framework" target="_blank"><img src="<?php echo SITE_PATH; ?>/img/PoweredBy_ZF_4LightBG.png" border="0"></a>&nbsp;&nbsp;&nbsp;<br />
</div>
