<?php
$this->headTitle()->setSeparator(' - ');
$this->headTitle(SITE_TITLE);
echo $this->headTitle() . "\n";
echo $this->headMeta() . "\n";

$this->headLink()->appendStylesheet(SITE_PATH . '/css/themes/ui-lightness/jquery-ui-1.8.16.custom.css') . "\n";
$this->headLink()->appendStylesheet(SITE_PATH . '/css/skins/tango/skin.css') . "\n";
$this->headLink()->appendStylesheet(SITE_PATH . '/css/jquery.imgareaselect-animated.css') . "\n";
$this->headLink()->appendStylesheet(SITE_PATH . '/css/jquery.modalbox.css') . "\n";
$this->headLink()->appendStylesheet(SITE_PATH . '/css/jquery.menu.css') . "\n";
$this->headLink()->appendStylesheet(SITE_PATH . '/css/site.css') . "\n";
echo $this->headLink() . "\n";

$this->headScript()->appendFile(SITE_PATH . '/js/jquery-1.7.1.min.js', 'text/javascript', array('charset' => 'utf-8')) . "\n";
$this->headScript()->appendFile(SITE_PATH . '/js/jquery-ui-1.8.16.custom.min.js', 'text/javascript', array('charset' => 'utf-8')) . "\n";
$this->headScript()->appendFile(SITE_PATH . '/js/jquery.blockUI.js', 'text/javascript', array('charset' => 'utf-8')) . "\n";
$this->headScript()->appendFile(SITE_PATH . '/js/jquery.imgareaselect.js', 'text/javascript', array('charset' => 'utf-8')) . "\n";
$this->headScript()->appendFile(SITE_PATH . '/js/jquery.easing.js', 'text/javascript', array('charset' => 'utf-8')) . "\n";
$this->headScript()->appendFile(SITE_PATH . '/js/jquery.lavalamp.js', 'text/javascript', array('charset' => 'utf-8')) . "\n";
$this->headScript()->appendFile(SITE_PATH . '/js/jquery.maskedinput.min.js', 'text/javascript', array('charset' => 'utf-8')) . "\n";
//$this->headScript()->appendFile(SITE_PATH . '/js/jquery.menu.js', 'text/javascript', array('charset' => 'utf-8')) . "\n";
$this->headScript()->appendFile(SITE_PATH . '/js/jquery.modalbox-1.2.1-min.js', 'text/javascript', array('charset' => 'utf-8')) . "\n";
$this->headScript()->appendFile(SITE_PATH . '/js/jquery.qtip-1.0.0-rc3.js', 'text/javascript', array('charset' => 'utf-8')) . "\n";
$this->headScript()->appendFile(SITE_PATH . '/js/jquery.ui.form.js', 'text/javascript', array('charset' => 'utf-8')) . "\n";

//$this->headScript()->appendFile(SITE_PATH . '/js/jquery/jquery.ui.draggable.min.js', 'text/javascript', array('charset' => 'utf-8')) . "\n";
//$this->headScript()->appendFile(SITE_PATH . '/js/jquery/jquery.ui.droppable.min.js', 'text/javascript', array('charset' => 'utf-8')) . "\n";
//$this->headScript()->appendFile(SITE_PATH . '/js/jquery/jquery.ui.mouse.min.js', 'text/javascript', array('charset' => 'utf-8')) . "\n";
//$this->headScript()->appendFile(SITE_PATH . '/js/overlib.js', 'text/javascript', array('charset' => 'utf-8')) . "\n";
$this->headScript()->appendFile(SITE_PATH . '/js/scripts.js', 'text/javascript', array('charset' => 'utf-8')) . "\n";
$this->headScript()->appendFile(SITE_PATH . '/js/head.js', 'text/javascript', array('charset' => 'utf-8')) . "\n";

$this->headScript()->appendFile(SITE_PATH . 'https://apis.google.com/js/plusone.js', 'text/javascript', array('charset' => 'utf-8')) . "\n";
$this->headScript()->appendFile(SITE_PATH . 'http://www.google.com/buzz/api/button.js', 'text/javascript', array('charset' => 'utf-8')) . "\n";
$this->headScript()->appendFile(SITE_PATH . 'http://platform.twitter.com/widgets.js', 'text/javascript', array('charset' => 'utf-8')) . "\n";
$this->headScript()->appendFile(SITE_PATH . 'http://platform.linkedin.com/in.js', 'text/javascript', array('charset' => 'utf-8')) . "\n";

//$this->headScript()->appendFile(SITE_PATH . '/js/jquery/jquery.jcarousel.js', 'text/javascript', array('charset' => 'utf-8')) . "\n";
//$this->headScript()->appendFile(SITE_PATH . '/js/jquery/jquery.tools.min.js', 'text/javascript', array('charset' => 'utf-8')) . "\n";
//$this->headScript()->appendFile(SITE_PATH . '/js/jquery/jquery.ui.datepicker-pt-BR.js', 'text/javascript', array('charset' => 'utf-8')) . "\n";
//$this->headScript()->appendFile(SITE_PATH . '/js/jquery/jquery.ui.timepicker.js', 'text/javascript', array('charset' => 'utf-8')) . "\n";

echo $this->headScript() . "\n";
?>
  <meta name="google-site-verification" content="I3YOqllRxvsdzvBbpxF049c0rtYLLj973MXOy1iJj40" />
  <link href="<?php echo SITE_PATH; ?>/favicon.ico" rel="shortcut icon" type="image/x-icon" />
  <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<!--[if IE]>
<style>
</style>

<![endif]-->