<?php echo $this->doctype() . "\n"; ?>
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<?php echo $this->render('head.phtml') . "\n"; ?>
	</head>
	<body>
		<noscript><h1>Por favor habilite ou use um navegador com suporte a javascript.</h1><h1>Please enable or use a browser that supports javascript.</h1><div style="margin:0 0 9999px 0;"></div></noscript>
		<header>
			<div id="topbar">
				<div id="top">
					<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=10,0,0,0" width="1002" height="100" id="top" align="middle">
						<param name="allowScriptAccess" value="sameDomain" />
						<param name="allowFullScreen" value="false" />
						<param name="movie" value="/img/logo/logo.swf" />
						<param name="quality" value="high" />
						<param name="bgcolor" value="#ffffff" />
						<embed src="/img/logo/logo.swf" quality="high" bgcolor="#ffffff" width="1002" height="100" name="top" align="middle" allowScriptAccess="sameDomain" allowFullScreen="false" type="application/x-shockwave-flash" pluginspage="http://www.adobe.com/go/getflashplayer" />
					</object>
				</div>
			</div>
			<div id="menubar">
				<div id="menulist">
<?php echo $this->render('menu.phtml') . "\n"; ?>
				</div>
			</div>
		</header>
		<content>
			<div id="layout">
				<div id="layoutcontent">
					<div id="left">
<?php echo $this->render('left.phtml') . "\n"; ?>
					</div>
					<div id="maincontent">
<?php echo $this->layout()->content; ?>
					    <div style="text-align:center;margin:0 auto;">
						<iframe src="http://smartad.mercadolivre.com.br/jm/SmartAd?tool=6109427&creativity=39401&new=Y&ovr=N&bgcol=EDC485&brdcol=000000&txtcol=006600&lnkcol=0000FF&hvrcol=FF0000&prccol=FF0000&word=cão&word=boxer&word=cachorro&site=MLB" width="728" height="90" scrolling="no" frameborder="0" marginheight="0" marginwidth="0"></iframe>
					    </div>
					    
					    <div style="text-align:center;margin:10px 0;">
						<script type="text/javascript"><!--
						google_ad_client = "ca-pub-6309972780716096";
						/* racaboxer bottom */
						google_ad_slot = "4839095380";
						google_ad_width = 728;
						google_ad_height = 90;
						//-->
						</script>
						<script type="text/javascript" src="http://pagead2.googlesyndication.com/pagead/show_ads.js"></script>
					    </div>

					</div>
				</div>
			</div>
		</content>
		<footer>
			<div id="bottombar"><div id="bottombarback"></div></div>
			<div id="footer">
<?php echo $this->render('footer.phtml') . "\n"; ?>
			</div>
			<div id="overDiv" style="position:absolute; visibility:hidden; z-index:1000;"></div>
		</footer>
		<!-- <script src="http://www.google-analytics.com/urchin.js" type="text/javascript"></script>
		<script type="text/javascript">_uacct = "UA-716804-1"; urchinTracker();</script> -->
		<script type="text/javascript">
			var _gaq = _gaq || [];
			_gaq.push(['_setAccount', 'UA-26864262-2']);
			_gaq.push(['_trackPageview']);
			(function() {
				var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
				ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
				var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
			})();
		</script>
	</body>
</html>
