					<div id="menu">
						<ul class="menu">
							<li><a href="<?php echo SITE_PATH; ?>/"><span>Home</span></a></li>
							<li><a href="<?php echo SITE_PATH; ?>/blog/" class="parent" title="Visitar o blog do site ra&ccedil;a boxer"><span>Blog</span></a>
								<ul>
<?php
require_once APP_PATH . '/models/Blog.php';
$modelblog = new Model_Blog();
$blogdata = $modelblog->fetchYears();

foreach ($blogdata as $blogyears => $blogyear):
?>
									<li><a href="<?php echo SITE_PATH; ?>/blog/<?php echo $blogyear['year']; ?>" title="<?php echo $blogyear['year']; ?>"><span><?php echo $blogyear['year']; ?></span></a></li>
<?php
endforeach;
?>
								</ul>
							</li>
							<li><a href="<?php echo SITE_PATH; ?>/galeria-de-fotos.html" class="parent"><span>Fotos</span></a>
								<ul>
									<li><a title="Veja as fotos" href="/galeria-de-fotos.html"><span>Veja as fotos</span></a></li>
									<li><a title="Envie sua foto" href="/galeria-enviar.html"><span>Envie sua foto</span></a></li>
								</ul>
							</li>
							<li><a href="javascript:void(0);" class="parent"><span>&Uacute;teis</span></a>
								<ul>
									<li><a title="Ajude nosso site anunciando sua propaganda aqui" href="/anuncie-aqui.html"><span>Anuncie Aqui</span></a></li>
									<li><a title="Aprenda no site ra&ccedil;a boxer como denunciar maus tratos aos animais" href="/como-denunciar-maus-tratos.html"><span>Como denunciar</span></a></li>
									<li><a title="Leia e se impressione com a lenda dos c&atilde;es boxer seguindo os dados b&iacute;blicos aqui no site ra&ccedil;a boxer" href="/a-lenda-do-cao-boxer-seguindo-os-dados-biblicos.html"><span>Lenda do Boxer</span></a></li>
									<!--<li><a href="/links.html" title="Veja os links que o site ra&ccedil;a boxer indica como amigos e preferidos"><span>Links</span></a></li>-->
									<li><a title="Escolha aqui no site ra&ccedil;a boxer o nome para seu novo cachorrinho" href="/nomes-de-caes.html"><span>Nomes de C&atilde;es</span></a></li>
									<li><a title="Saiba qual a origem de um c&atilde;o boxer aqui no site ra&ccedil;a boxer" href="/origem.html"><span>Origem da Ra&ccedil;a</span></a></li>
								</ul>
							</li>
							<li><a href="<?php echo SITE_PATH; ?>/contato.html" title="Entrar em contato com o site ra&ccedil;a boxer"><span>Contato</span></a></li>
						</ul>
					</div>
<?php
/*
$imgfile = "img/logo/banner84x100.gif";
$imgbinary = fread(fopen($imgfile, "r"), filesize($imgfile));
echo '<img src="data:image/gif;base64,' . base64_encode($imgbinary) . '" />';
die(base64_encode($imgbinary));
*/
?>