 <ul id="nav">
  <li class="top"><a class="links top_link" href="<?php echo SITE_PATH; ?>/" onmouseover="return overlib('Página Inicial');" onmouseout="return nd();"><span>Home</span></a></li>
  <li class="top"><a class="links top_link" href="<?php echo SITE_PATH; ?>/index/portfolio" onmouseover="return overlib('Portfólio de clientes');" onmouseout="return nd();"><span>Portfólio</span></a></li>
  <li class="top"><a class="links top_link" href="<?php echo SITE_PATH; ?>/index/scripts" onmouseover="return overlib('Html, jQuery, PHP, Shell, etc...');" onmouseout="return nd();"><span>Scripts</span></a>
   <ul class="sub">
    <li><a class="links" href="<?php echo SITE_PATH; ?>/scripts/hexcode-decript.html" onmouseover="return overlib('Aprenda a desencriptar links dos sites de download');" onmouseout="return nd();"><span>HexCode Decript</span></a></li>
    <li><a class="links" href="<?php echo SITE_PATH; ?>/scripts/reverse-string.html" onmouseover="return overlib('Como desinverter links de download dos sites de filmes');" onmouseout="return nd();"><span>Reverse String</span></a></li>
    <li><a class="links" href="<?php echo SITE_PATH; ?>/scripts/text-counter.html" onmouseover="return overlib('Contagem de quantidade de caractéres');" onmouseout="return nd();"><span>Text Counter</span></a></li>
   </ul>
  </li>
  <li class="top"><a class="links top_link" href="<?php echo SITE_PATH; ?>/index/contato" onmouseover="return overlib('Entre em contato comigo');" onmouseout="return nd();"><span>Contato</span></a></li>
 </ul>
