<?php 
if(count($this->datalist) > 0)
{
?>
<script type="text/javascript">
var total = 0;
$(document).ready(function()
{
    $(".productItem").draggable({ helper: "clone", opacity: "0.5" });

    $("#dropZone").droppable({
    	accept: ".productItem",
    	hoverClass: "dropHover",
    	drop: function(ev, ui)
    	{
    		//var droppedItem = ui.draggable.clone().addClass("droppedItem").attr('style', 'border-bottom:2px 0;border-style:dotted #E85C06; border-top:2px 0;border-style:dotted #E85C06; border-left:0; border-right:0;');
    		var droppedItem = ui.draggable.clone().addClass("droppedItem").attr('style', 'border:2px dotted #E85C06;margin:10px auto 0;width:724px;');
    		var productCode = droppedItem[0].attributes["code"].nodeValue;
    		//var productPrice = getFormattedPrice(droppedItem[0].attributes["price"].nodeValue);
    		var productPrice = droppedItem[0].attributes["price"].nodeValue;
    		var removeLink = document.createElement("a");
    		removeLink.innerHTML = "Remove";
    		removeLink.className = "deleteLink";
    		removeLink.href = "#";
    		removeLink.onclick = function()
    		{
    			$("#dropZone").children().remove("#" + droppedItem[0].attributes["id"].nodeValue);
    			updateTotal(productPrice * (-1));
    		}

    		droppedItem[0].appendChild(removeLink);
    		$(this).append(droppedItem);
    		updateTotal(productPrice);
    	}
	});

	$(".addtocart").click(function(){
	});
    
    $("#total").html("R$ " + total.toFixed(2));
});

function updateTotal(price)
{
	total += parseFloat(price);
	$("#total").html("R$ " + total.toFixed(2));
	$("#shoppingCartTotal").effect("bounce");
}

function listSelectedItems()
{
	var itemsInShoppingCart = $("#dropZone div");

	for(i=0;i<=itemsInShoppingCart.length-1;i++)
	{
		alert(itemsInShoppingCart[i].attributes["code"].nodeValue);
		alert(itemsInShoppingCart[i].attributes["price"].nodeValue);
	}
}
</script>
<?php
	echo "<div id=\"products\">\n";
	
	foreach($this->datalist as $dl)
	{
		$price = number_format($dl['price'], 2, ',', '.');
		
		echo " <div class=\"productItem\" price='" . $price . "' code='item_" . $dl['id'] . "' id='item_" . $dl['id'] . "' ";
		echo " style=\"border:2px dotted #E85C06;margin:1px 0;width:738px;\">\n";
		echo "  <ul>\n";
		echo "   <li>Código :" . $dl['id'] . "</li>\n";
		echo "   <li>Nome: " . utf8_encode($dl['name']) . "</li>\n";
		echo "   <li>Descrição: " . utf8_encode($dl['description']) . "</li>\n";
		echo "   <li>Preço: R$ " . $price . "</li>\n";
		echo "   <li class=\"addtocart\" id=\"c_" . $dl['id'] . "\"><u>Adicionar ao carrinho</u></li>\n";
		echo "  </ul>\n";
		echo " </div>\n";
	}
	
	echo "</div>\n";

	echo "<div id=\"dropZone\" style=\"border:2px dotted #E85C06;margin:10px 0;width:738px;\">\n";
	echo "<h1 style=\"text-align:center;\">Carrinho de compras</h1>\n";
	echo "</div>\n";
	
	echo "<div id=\"shoppingCartTotal\" style=\"border:2px dotted #E85C06;height:100px;margin:10px 0;width:738px;\">\n";
	echo " <h1 style=\"text-align:center;\">Total</h1>\n";
	echo " <div id=\"total\">\n";
	echo " </div>\n";
	echo "</div>\n";
?>



<?php 
}
else
{
?>
<div id="products"><h1>Não existem produtos a exibir</h1></div>
<?php 
}
?>
