<div id="fotoupload">
 <h1 id="headh1" style="text-align:center;">Envie a foto do seu cachorro</h1>
 <div style="margin:0 auto;width:716px;"><img src="" id="thumbnail" style="border:3px solid #E85C06;display:none;width:716px;" /></div>
 <form id="fotoupload_frm" name="fotoupload_frm" method="post" enctype="multipart/form-data" action="/galeria-enviar.html" accept="image/gif, image/jpeg, image/jpg, image/png">
  <b>Clique no bot&atilde;o abaixo, escolha a foto e espere</b><br />
  <input id="fotodocao" name="fotodocao" type="file" size="73" />
  <input id="fotoupload_btn" name="fotoupload_btn" type="button" value="Enviar" />
  <hr />
  <p><b>Tipos de fotos:</b> S&atilde;o permitidas as fotos em <b>GIF</b>, <b>JPG</b>, <b>JPEG</b> e <b>PNG</b>.</p>
  <p><b>Importante:</b> espere terminar de carregar a imagem e quando aparecer a foto recorte como voc&ecirc; quer que apare&ccedil;a, preencha os dados e clique em salvar.</p>
 </form>
</div>
<div id="fotoupload_progress"></div>
<div id="fotoupload_result" style="display:none;"></div>
<input type="button" style="display:none;" id="fakebutton" onclick="hiddenfunction();" />
<br />
<p>Se voc&ecirc; n&atilde;o completar os passos acima a foto do seu c&atilde;o <b>N&Atilde;O</b> ir&aacute; para o site.</p>
<p>Assim que aprovada a imagem, voc&ecirc; receber&aacute; um email confirmando e um link do site onde ela estar&aacute;.</p>
<p>Divirta-se.</p>

