<?php 
if(count($this->datalist) > 0)
{
?>
<h1 style="text-align:center;">Clique nas imagens para ampliar</h1>
<p style="text-align:justify;">Clicando no n&uacute;mero da foto voc&ecirc; poder&aacute;: ver mais detalhes do c&atilde;o da foto, fazer coment&aacute;rios, compartilhar no facebook, twitter, etc</p>
<ul id="imageslist">
<?php
	$anoatual = "";
	
	foreach($this->datalist as $dl)
	{
?>
 <li class="thumbs">
  <img class="thumbnails" src="/img/dogs/<?php echo $dl['path']; ?>" title="Clique para ampliar" /><br />
  <a title="veja mais detalhes" href="/galeria/foto_<?php echo $dl['id']; ?>.html"><strong><?php echo $dl['id']; ?></strong></a>
 </li>
<?php
	}
}
?>
</ul>

<div class="menucenterclear"></div>

<div id="pagination">
 <a class="button" href="/galeria-enviar.html" title="clique aqui para enviar a foto do seu c&atilde;o para aparecer aqui no Ra&ccedil;a Boxer">Envie a sua foto</a>
</div>

<div class="menucenterclear"></div>

<div id="paginationdiv">
<?php
if($this->paginator->count() > 1) echo $this->paginationControl($this->paginator, 'Elastic', 'images' . DS . 'pagination.phtml');
?>
</div>
