<table class='sample' align='center' style="margin:40px 0;width:742px !important;">
 <tbody>
  <tr>
   <td style="text-align:center;">
   
<!-- First page link -->
<?php
if(isset($this->previous))
{
?>
<span class="previous"><a class="links button" href="/galeria-de-fotos.html?p=<?php echo $this->first; ?>" title="Primeira Página">|&laquo;</a></span>
<?php 
}
else
{
?>
<span class="previous-off button">|&laquo;</span>
<?php 
}
?>

<!-- Previous page link -->
<?php
if (isset($this->previous))
{
?>
<span class="previous"><a class="links button" href="/galeria-de-fotos.html?p=<?php echo $this->previous; ?>" title="Página Anterior">&laquo;</a></span>
<?php 
}
else
{
?>
<span class="previous-off button">&laquo;</span>
<?php 
}
?>

<!-- Numbered page links -->
<?php 
foreach ($this->pagesInRange as $page)
{
	if ($page != $this->current)
	{	
?>
<a class="links button" href="/galeria-de-fotos.html?p=<?php echo $page; ?>" title="Ir para página <?php echo $page; ?>');"><?php echo $page; ?></a>
<?php 
	}
	else
	{
?>
<span class="active button"><?php echo $page . " "; ?></span>
<?php 
	}
}
?>

<!-- Next page link -->
<?php
if (isset($this->next))
{
?>
<span class="next"><a class="links button" href="/galeria-de-fotos.html?p=<?php echo $this->next; ?>" title="Próxima Página">&raquo;</a></span>
<?php 
}
else
{
?>

<span class="next-off button">&raquo;</span>
<?php 
}
?>

<!-- Last page link -->
<?php
if (isset($this->next))
{
?>
<span class="next"><a class="links button" href="/galeria-de-fotos.html?p=<?php echo $this->last; ?>" title="Última Página">&raquo;|</a></span>
<?php 
}
else
{
?>
<span class="next-off button">&raquo;|</span>
<?php 
}
?>
   </td>
  </tr>
  <tr>
   <td style="text-align:center;"><span class="previous-off button">Página <?php echo $this->current; ?> de <?php echo $this->last; ?></span></td>
  </tr>
 </tbody>
</table>
