<?php
$this->title = "Busca";
$this->headTitle($this->title);
?>
     <script type="text/javascript">
		<!--
		$(document).ready(function(){
			//$("#slider1").agcRoller ({ time : 6000 }); 
		});
		//-->
     </script>
     <div id="slider1">
<?php
/**
 * NOTICIAS LIST
 */

if(count($this->noticiasdata) > 0)
{
	$c = 0;
	foreach($this->noticiasdata as $noticias)
	{
?>
       <div id="noticia_<?php echo $c; ?>" class="noticias">
        <div class="titulo"><a href="<?php echo SITE_PATH; ?>/noticias/?id=<?php echo $noticias['idnoticia'] ?>"><?php echo utf8_encode(stripslashes($noticias['titulo'])); ?> - <?php echo $noticias['data_publicacao']; ?></a></div>
<?php
		if(($noticias['imagem_materia'] <> '') && is_file(SITE_PATH . "/img/_noticias/" . $noticias['imagem_materia']))
		{
			//echo "        <div class=\"imagem\">\n";
			//echo "         <a class=\"openmodalbox\" href=\"javascript:void(0);\">\n";
			echo "          <center><img src=\"" . SITE_PATH . "/img/_noticias/" . $noticias['imagem_materia'] . "\" style=\"margin-top:0 auto !important;max-height:150px !important;\" /></center>\n";
			//echo "          <span class=\"modalboxContent\"><img class=\"modalgallery\" src=\"" . SITE_PATH . "/img/_noticias/" . $noticias['imagem_materia'] . "\" style=\"border:1px solid #9A7575;\" /></span>\n";
			//echo "         </a>\n";
			//echo "        </div>\n";
		}
?>
        <div class="corpo"><?php echo utf8_encode(stripslashes($noticias['corpo'])); ?></div>
        <div class="autor">
         <div class="autorcat">Por: <span class="autorname"><?php echo utf8_encode(stripslashes($noticias['nomefonte'])); ?></span>
		 <!-- | Categoria: <span class="catname">cat, tac, act, atc</span> --></div>
         <!-- <div class="comments"></div> -->
		 <?php
		 $title = utf8_encode($noticias['titulo']);
		 $link = urlencode("http://" . $_SERVER['SERVER_NAME'] . SITE_PATH . "/noticias/?id=" . $noticias['idnoticia']);
		 include APP_PATH . "/class/bookmarklets.php";
		 ?>
        </div>
       </div>
<?php 
		$c++;
	}
}
else
{
?>
      <div class="msg red"><div style="margin:0 auto;width:420px;">Nada encontrado na sua busca, por favor tente novamente com outros critérios.</div></div>
<?php
}
?>
     </div>
     <div id="paginationdiv">
<?php
if($this->paginator <> 'T' && $this->paginator->count() > 1) echo $this->paginationControl($this->paginator, 'Elastic', 'times' . DS . 'pagination.phtml');
?>
     </div>
