<?php $row = $this->row; ?>
  <td id='td_<?php echo $this->div; ?>' colspan='5' style='cursor:pointer;width:944px;'>
   <input style="font-size:0.9em;" type='text' name='namenew_<?php echo $row['id']; ?>' id='namenew_<?php echo $row['id']; ?>' value='<?php echo stripslashes($row['name']); ?>' onkeyup='updateemails("<?php echo $row['id']; ?>", "<?php echo $this->div; ?>", event);' size='<?php echo strlen($row['name']); ?>' />
   <input style="font-size:0.9em;" type='text' name='emailnew_<?php echo $row['id']; ?>' id='emailnew_<?php echo $row['id']; ?>' value='<?php echo stripslashes($row['email']); ?>' onkeyup='updateemails("<?php echo $row['id']; ?>", "<?php echo $this->div; ?>", event);' size='<?php echo strlen($row['email']); ?>' />
   <input type='hidden' name='id' id='id' value='<?php echo $row['id']; ?>' />
   <a class="button" onclick='updatememails("<?php echo $row['id']; ?>", "<?php echo $this->div; ?>");'>Ok</a>
   <a class="button" onclick="canceledit('<?php echo $row['id']; ?>', '<?php echo $this->div; ?>', 'emails');">Cancel</a>
   <b class="error">ESC to close</b>
   <b class="success">ENTER to save</b>
   <script type='text/javascript'>$(".button").button();</script>
  </td>
  <td class='tdpag-icons' onclick="javascript:removeemails('<?php echo $row['id']; ?>','<?php echo $this->div; ?>');">
   <div class="ui-state-default ui-corner-all pag-icons"><span class="ui-icon ui-icon-trash" title="Remove ID: <?php echo $row['id']; ?>"></span></div>
  </td>
