<?php
$data = $this->row;
?>
  <td class='tdpag-icons' style='width:40px;'><?php echo $data['id']; ?></td>
  <td class="tdtextlink" id='td_<?php echo $this->div; ?>' style='width:436px;' onclick="javascript:editpageinline('emails', '<?php echo $data['id']; ?>', '<?php echo $this->div; ?>');"><?php
if(!empty($name)) echo str_ireplace($name, "<b class='filterwords'>" . $name . "</b>", stripslashes($data['name'])); 
else echo stripslashes($data['name']);
?></td>
  <td class="tdtextlink" style='width:430px;' onclick="javascript:sendmail('<?php echo $data['name']; ?>','<?php echo $data['email']; ?>');" title="SendMail: <?php echo $data['id']; ?>">
<?php
if(!empty($email)) echo str_ireplace($email, "<b class='filterwords'>" . $email . "</b>", stripslashes($data['email'])); 
else echo stripslashes($data['email']);
?>
  </td>
  <td class='tdpag-icons' id="activeonoff_<?php echo $data['id']; ?>">
   <div class="ui-state-default ui-corner-all pag-icons" onclick="javascript:activeonoff('emails','<?php echo $data['id']; ?>','<?php echo $this->div; ?>');"><span class="ui-icon ui-icon-<?php if($data['active'] == '1'){ echo 'check'; } else{ echo 'cancel'; } ?>" title="Active OnOff ID: <?php echo $data['id']; ?>"></span></div>
  </td>
  <td class='tdpag-icons' onclick="javascript:editpageinline('emails','<?php echo $data['id']; ?>','<?php echo $this->div; ?>');">
   <div class="ui-state-default ui-corner-all pag-icons"><span class="ui-icon ui-icon-pencil" title="Edit ID: <?php echo $data['id']; ?>"></span></div>
  </td>
  <td class='tdpag-icons' onclick="javascript:removeemails('<?php echo $data['id']; ?>','<?php echo $this->div; ?>');">
   <div class="ui-state-default ui-corner-all pag-icons"><span class="ui-icon ui-icon-trash" title="Remove ID: <?php echo $data['id']; ?>"></span></div>
  </td>
