<?php
$denymessage = $this->denymessage;
if(!empty($denymessage)){ echo "<div class='error'>" . $denymessage . "</div>"; exit; }

$pagename = $this->pagename;
$title = $this->title;
echo "<script>newfieldcount = " . count($this->datalist) . ";</script>\n";
?>
<script type="text/javascript">
$("#menu").find("li").each(function(){ $(this).removeClass("ui-tabs-selected ui-state-active"); });
$("#blo").addClass("ui-tabs-selected ui-state-active");
$(".ui-icon").hover(
	function(){ if($(this).parent().get(0).tagName == 'DIV'){ $(this).parent().addClass("ui-state-hover"); } },
	function(){ if($(this).parent().get(0).tagName == 'DIV'){ $(this).parent().removeClass("ui-state-hover"); } }
);
</script>
<br />
<table class='sample' style="margin:0 auto;">
 <tbody>
  <tr>
   <td style="text-align:left;width:25%;"><a href="#" class="button" onclick="javascript:addpage('blog');" title="Add New">Add New</a></td>
   <td style="text-align:center;width:80%;">
    <form id="search" method="post" action="">
     Filter: <input type="text" id="ftitle" name="ftitle" value="" onkeypress="javascript:filter('blog',event);" size="50" />
     <a class="button" onclick="filterm('blog');" title="Ok">Ok</a>
    </form>
   </td>
  </tr>
 </tbody>
</table>

<table class='sample' style="margin:0 auto;" id="grid">
 <thead>
  <tr>
   <th style='width:40px;'>ID</th>
   <th style='width:810px;'>Title</th>
   <th style='width:137px;'>Date</th>
   <th style='width:19px;'>&nbsp;</th>
   <th style='width:19px;'>&nbsp;</th>
   <th style='width:19px;'>&nbsp;</th>
   <th style='width:19px;'>&nbsp;</th>
  </tr>
 </thead>
 <tbody id="list">
<?php
if(count($this->datalist) > 0)
{
	$c = 0;
	foreach ($this->datalist as $data)
	{
		if($data['display'] == '1')
		{
			if(($c % 2) == 0){ $over = "overa"; }
			else{ $over = "overb"; }
		}
		else{ $over = "noover"; }
?>
 <tr id='list_<?php echo $c; ?>' class="<?php echo $over; ?>" onmouseover="this.className='over'" onmouseout="this.className='<?php echo $over; ?>'">
  <td class='tdpag-icons' style='width:40px;'><?php echo $data['id']; ?></td>
  <td style='width:810px;'>
   <a href="http://<?php echo $_SERVER['SERVER_NAME']; ?>/blog/<?php echo date("Y-m-d", strtotime($data['cdate'])); ?>/<?php echo $data['id'] . '-' . $data['url']; ?>.html" target="_blank" title="Open: <?php echo utf8_decode(stripslashes($data['title'])); ?>"><?php 
if(!empty($title)) echo str_ireplace($title, "<b class='filterwords'>" . $title . "</b>", utf8_decode(stripslashes($data['title']))); 
else echo utf8_decode(stripslashes($data['title']));
?></a>
  </td>
  <td style='width:137px;'><?php $cdate = strtotime($data['cdate']); $cdate = date('d/m/Y g:ia', $cdate); echo $cdate; ?></td>
  <td class='tdpag-icons' onclick="javascript:previewpage('blog','<?php echo $data['id']; ?>');">
   <div class="ui-state-default ui-corner-all pag-icons"><span class="ui-icon ui-icon-newwin" title="Preview ID: <?php echo $data['id']; ?>"></span></div>
  </td>
  <td class='tdpag-icons' id="displayonoff_<?php echo $data['id']; ?>">
   <div class="ui-state-default ui-corner-all pag-icons" onclick="javascript:displayonoff('blog','<?php echo $data['id']; ?>','<?php echo $c; ?>');"><span class="ui-icon ui-icon-<?php if($data['display'] == '1'){ echo 'check'; } else{ echo 'cancel'; } ?>" title="Enable/Disable Display ID: <?php echo $data['id']; ?>"></span></div>
  </td>
  <td class='tdpag-icons' onclick="javascript:editpage('blog', '<?php echo $data['id']; ?>');">
   <div class="ui-state-default ui-corner-all pag-icons"><span class="ui-icon ui-icon-pencil" title="Edit ID: <?php echo $data['id']; ?>"></span></div>
  </td>
  <td class='tdpag-icons' onclick="javascript:removepage('blog','<?php echo $data['id']; ?>','<?php echo $c; ?>');">
   <div class="ui-state-default ui-corner-all pag-icons"><span class="ui-icon ui-icon-trash" title="Remove ID: <?php echo $data['id']; ?>"></span></div>
  </td>
 </tr>
<?php
		$c++;
	}
}
else
{
?>
 <tr id="list_empty" class="<?php echo $dcolors[$d]; ?>" onmouseover="this.className='over'" onmouseout="this.className='<?php echo $dcolors[$d]; ?>'">
  <td colspan='7' style='text-align:center;'>
   <a class="button" onclick="javascript:addpage('blog');" title="Add New">Nothing in database, click here to add</a>
  </td>
 </tr>
<?php
 } ?>
 </tbody>
</table>

<?php
if($this->paginator->count() > 1) echo $this->paginationControl($this->paginator, 'Elastic', 'admin' . DS . 'pagination.phtml');
?>
