<?php
$pagename = $this->pagename;
$title = $this->title;
echo "<script>newfieldcount = " . count($this->datalist) . ";</script>\n";
?>
<script type="text/javascript" src="/js/admin-pos-load.js"></script>
<script type="text/javascript">
$("#menu").find("li").each(function(){ $(this).removeClass("ui-tabs-selected ui-state-active"); });
$("#new").addClass("ui-tabs-selected ui-state-active");
$(".ui-icon").hover(
	function(){ if($(this).parent().get(0).tagName == 'DIV'){ $(this).parent().addClass("ui-state-hover"); } },
	function(){ if($(this).parent().get(0).tagName == 'DIV'){ $(this).parent().removeClass("ui-state-hover"); } }
);
</script>
<br />
<table class='sample' style="margin:0 auto;">
 <tbody>
  <tr>
   <td style="text-align:left;width:25%;"><a href="#" class="button" onclick="javascript:addpage('newsletter');" title="Add New">Add New</a></td>
   <td style="text-align:center;width:80%;">
    <form id="search" method="post" action="">
     Filter: <input type="text" id="ftitle" name="ftitle" value="" onkeypress="javascript:filter('newsletter',event);" size="50" />
     <a class="button" onclick="filterm('newsletter');" title="Ok">Ok</a>
	</form>
   </td>
  </tr>
 </tbody>
</table>

<table class='sample' style="margin:0 auto;" id="grid">
 <thead>
  <tr>
   <th style='width:40px;'>ID</th>
   <th style='width:587px;'>Title</th>
   <th style='width:120px;'>Sended</th>
   <th style='width:120px;'>Sended Times</th>
   <th style='width:120px;'>Date</th>
   <th style='width:19px;'>&nbsp;</th>
   <th style='width:19px;'>&nbsp;</th>
   <th style='width:19px;'>&nbsp;</th>
   <th style='width:19px;'>&nbsp;</th>
  </tr>
 </thead>
 <tbody id="list">
<?php
if(count($this->datalist) > 0)
{
	$c = 0;
	foreach ($this->datalist as $data)
	{
		if($data['display'] == '1')
		{
			if(($c % 2) == 0){ $over = "overa"; }
			else{ $over = "overb"; }
		}
		else{ $over = "noover"; }
?>
 <tr id='list_<?php echo $c; ?>' class="<?php echo $over; ?>" onmouseover="this.className='over'" onmouseout="this.className='<?php echo $over; ?>'">
  <td style='text-align:center;width:40px;'><?php echo $data['id']; ?></td>
  <td style='width:587px;'>
   <?php 
if(!empty($title)) echo str_ireplace($title, "<b class='filterwords'>" . $title . "</b>", (stripslashes($data['title']))); 
else echo (stripslashes($data['title']));
?>
  </td>
  <td style='width:120px;'><?php if($data['sended'] == '0000-00-00 00:00:00'){ echo "Never"; } else { echo date('d/m/Y g:ia', strtotime($data['sended'])); } ?></td>
  <td style='width:120px;'><?php echo $data['sended_times']; ?></td>
  <td style='width:120px;'><?php echo date('d/m/Y g:ia', strtotime($data['cdate'])); ?></td>
  <td class='tdpag-icons' onclick="javascript:previewpage('newsletter','<?php echo $data['id']; ?>');">
   <div class="ui-state-default ui-corner-all pag-icons"><span class="ui-icon ui-icon-newwin" title="Preview ID: <?php echo $data['id']; ?>"></span></div>
  </td>
  <td class='tdpag-icons' id="newsletter_<?php echo $data['id']; ?>">
   <div class="ui-state-default ui-corner-all pag-icons" onclick="javascript:sendnewsletter('<?php echo $data['id']; ?>');"><span class="ui-icon ui-icon-mail-closed" title="Send Newsletter ID: <?php echo $data['id']; ?>"></span></div>
  </td>
  <td class='tdpag-icons' onclick="javascript:editpage('newsletter', '<?php echo $data['id']; ?>');">
   <div class="ui-state-default ui-corner-all pag-icons"><span class="ui-icon ui-icon-pencil" title="Edit ID: <?php echo $data['id']; ?>"></span></div>
  </td>
  <td class='tdpag-icons' onclick="javascript:removepage('newsletter','<?php echo $data['id']; ?>','<?php echo $c; ?>');">
   <div class="ui-state-default ui-corner-all pag-icons"><span class="ui-icon ui-icon-trash" title="Remove ID: <?php echo $data['id']; ?>"></span></div>
  </td>
 </tr>
<?php
		$c++;
	}
}
else
{
?>
 <tr id="list_empty" class="<?php echo $dcolors[$d]; ?>" onmouseover="this.className='over'" onmouseout="this.className='<?php echo $dcolors[$d]; ?>'">
  <td colspan='7' style='text-align:center;'><a class="button openmodalbox" onclick="javascript:void(0);">Nothing in database, click here to add<input type="hidden" name="ajaxhref" value="/admin/addnewsletter" /></a></td>
 </tr>
<?php
 } ?>
 </tbody>
</table>

<div id="paginationdiv">
<?php
if($this->paginator->count() > 1) echo $this->paginationControl($this->paginator, 'Elastic', 'admin' . DS . 'pagination.phtml');
?>
</div>
