<link href="/css/jquery/jquery.ui.all.css" media="screen" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="/js/jquery/jquery-1.6.4.js"></script>
<script type="text/javascript" src="/js/jquery/jquery-ui-1.8.11.custom.min.js"></script>
<script type="text/javascript">
(function(){
	if($('#selecionaremails').length){ $('#selecionaremails').remove(); }
	var scri = document.createElement('script');
	scri.type = 'text/javascript';
	scri.id = 'selecionaremails';
	scri.async = true;
	scri.src = '/js/admin/selecionaremails.js';
	(document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(scri);
})();
</script>
<link href="/css/admin-selemails.css" media="screen" rel="stylesheet" type="text/css" />
<center><a href='javascript:void(0);' id='descertodos' onclick='descertodos();'>Descer Todos</a></center>
<div id="listdiv" style="float:left;margin:0;padding:0;position:relative;width:100%;">
<?php
if(count($this->datalist) > 0)
{
	$c=1;
	foreach ($this->datalist as $data)
	{
?>
  <div id="email_<?php echo $data['id']; ?>" class="emails" onclick="emailselecionar('<?php echo $data['id']; ?>', '<?php echo $data['email']; ?>');" title="<?php echo $data['id'] . " - " . $data['email']; ?>">
   <?php echo $c . ' - ' . stripslashes($data['email']); ?>
  </div>
<?php
		$c++;
	}
}
?>
</div>
