<?php 
$urltoback = $_SERVER['HTTP_REFERER'] != "" ? $_SERVER['HTTP_REFERER'] : "/blog/";

if(count($this->datalist) > 0)
{
	$anoatual = "";
	foreach($this->datalist as $dl)
	{
		$ano = date("Y", strtotime($dl['cdate']));
		
		if($ano <> $anoatual)
		{
?>
    <strong><a href="/blog/<?php echo $ano; ?>" title="Ver postagens do ano <?php echo $ano; ?> no Blog"><?php echo $ano; ?></a></strong>&nbsp;&nbsp;
<?php
		}
		
		$anoatual = $ano;
	}
}
?>
<br /><br /><br />